[package]
name = "aiy-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
tch = "0.14.0"
diffusers = { git = "https://github.com/zgljl2012/diffusers-rs", rev = "3e9dacdb8370c3bfbbca403b719d25d73c7644bb"}
regex = "1.10.2"
clap = { version = "4.4.7", features = ["derive"] }
