
vocab_size = 49408
embed_dim = 768
intermediate_size = 3072
max_position_embeddings = 77
# ignore
pad_with = "!"
num_hidden_layers = 12
num_attention_heads = 12
projection_dim = 768
activation = "QuickGelu"
